name: Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the project
        run: cargo build --release

      - name: List target/release directory
        run: ls -la target/release

      - name: Create release directory
        run: mkdir release

      - name: Copy executable to release directory
        run: cp target/release/battery-life-tracker release/

      - name: Create ZIP file
        run: zip -j release/battery-life-tracker.zip release/battery-life-tracker

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/battery-life-tracker.zip
          asset_name: battery-life-tracker.zip
          asset_content_type: application/zip
