name: Create release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install target for Windows
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build the project for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              target/x86_64-pc-windows-gnu/release/battery-life-tracker.exe#battery-life-tracker.exe
